### ISSUE TITLE
Black Screen when breaking blocks with the correct tool (using shaders)

### ISSUE THREAD

**Issue by Crishuuwu** [Freebi85/Explorico_light#4]
Idk the reason but each time i use the correct tool for mining, digging, etc the game shows a black screen until the breaking animation finish.

**Comment by Freebi85** [comment]
That’s a werid one but i don’t support shaders by default. Right now it’s difficult to use them correctly because astral sorcery changes the rendering system of the sky and there are issues on this alpha or beta version right now. Maybe with upcoming updates!

Join our explorico discord for further tech support, it’s easier to troubleshoot things like this 😉

Cheers 🍻
